/* DOC

   test_facilities.c   - Auxiliary routines for the test
                         programs generated with "testmake"

   Copyright (C) 2002 Arjen Markus

   Arjen Markus


   General information:
   This module contains routines and functions that are used by the
   test programs generated by "testmake".

  ENDDOC
*/

/*
   $Author$
   $Date$
   $Source$
*/

#include <stdlib.h>
#include <stdio.h>
#include <stdio.h>

#include "test_fac.h"
#undef malloc

typedef struct _MallocData {
   void   * pmem ;   /* Pointer to the allocated memory */
   size_t   size ;   /* Size of the allocated memory block */
} MallocData, *MallocDataPtr ;

#define MAX_MALLOCS 10000
static MallocData malloc_data[MAX_MALLOCS] ;
static int        malloc_idx = 0 ;

/* --------------------------------------------------------------------
   Function: test__malloc_reset()
   Author:   Arjen Markus
   Purpose:  Reset the malloc_data index
   Context:  Used in initialise()
   Summary:
             Free all the allocated memory blocks and reset the
             index
-------------------------------------------------------------------- */
void test__malloc_reset( void )
{
   int i ;

   for ( i = 0 ; i < malloc_idx ; i ++ )
   {
      free( malloc_data[i].pmem ) ;
   }

   malloc_idx = 0 ;
}

/* --------------------------------------------------------------------
   Function: test__find_pointer()
   Author:   Arjen Markus
   Purpose:  Find the pointer in the malloc_data array
   Context:  Used internally
   Summary:
             Loop through the allocated memory blocks and see if the
             pointer is known
-------------------------------------------------------------------- */
int test__find_pointer( void *pmem )
{
   int i ;
   int idx ;

   idx = -1 ;

   for ( i = 0 ; i < malloc_idx ; i ++ )
   {
      if ( malloc_data[i].pmem == pmem )
      {
         idx = i ;
         break   ;
      }
   }

   return idx ;
}

/* --------------------------------------------------------------------
   Function: test__malloc()
   Author:   Arjen Markus
   Purpose:  Allocate memory and register this
   Context:  Used instead of malloc()
   Summary:
             Allocate the amount of memory that is required
             and register both the amount and the pointer for
             later reference.
-------------------------------------------------------------------- */
void *
test__malloc( size_t size )
{
   void * pmem ;

   pmem = malloc( size ) ;
   malloc_data[malloc_idx].pmem = pmem ;
   malloc_data[malloc_idx].size = size ;

   if ( pmem == NULL )
   {
      fprintf( stderr, "Failed to allocate memory of size %ul\n",
         (unsigned long) size ) ;
      exit(1) ;
   }

   malloc_idx ++ ;
   if ( malloc_idx >= MAX_MALLOCS )
   {
      fprintf( stderr, "Too many allocated memory blocks\n" ) ;
      exit(1) ;
   }

   return pmem ;
}

/* --------------------------------------------------------------------
   Function: test__copy()
   Author:   Arjen Markus
   Purpose:  Copy the contents of the public variable
   Context:  Used to save the initial data
   Summary:
             Check if the public variable is an allocated variable.
             If so, get the same amount of data for it.
             Copy the contents.
   Note:
             This scheme will fail when arrays of pointers are
             being used. This is the reason why - in principle
             - a hook is available for more complicated data types.
             To do: implement a hook mechanism!
-------------------------------------------------------------------- */
void
test__copy(
   void   ** public_var,  /* I public variable - contents must be saved */
   void   ** copy_var,    /* O variable that will hold the information */
   char   * var_type,     /* I type of variable */
   size_t   var_size      /* I static size of the variable */
   )
{
   int idx ;

   /* Check if the public variable is an allocated array
   */
   idx = test__find_pointer( (*public_var) ) ;
   if ( idx >= 0 )
   {
      (*copy_var) = test__malloc( malloc_data[idx].size ) ;
      memmove( (*copy_var), (*public_var),
         malloc_data[idx].size ) ;
   }
   else
   {
      memmove( (void *) copy_var, (void *) public_var, var_size ) ;
   }
}

/* --------------------------------------------------------------------
   Function: test__equal()
   Author:   Arjen Markus
   Purpose:  Compare the public variable with the saved variable
   Context:  Used to check if the public variable has changed
   Summary:
             Compare the variables bytes by bytes. Return 1 if all bytes
             are equal, otherwise 0.
-------------------------------------------------------------------- */
int
test__equal(
   void   ** public_var,  /* I public variable */
   void   ** copy_var,    /* I variable with the initial values */
   char   *  var_type,    /* I type of variable */
   size_t    var_size     /* I static size of the variable */
   )
{
   int idx     ;
   int i       ;
   int nobytes ;
   int equal   ;

   /* Check if the public variable is an allocated array
   */
   idx = test__find_pointer( *public_var ) ;
   if ( idx >= 0 )
   {
      nobytes = (int) malloc_data[idx].size ;
      equal   = (memcmp( (*public_var), (*copy_var), nobytes ) == 0 ) ;
   }
   else
   {
      nobytes = (int) var_size ;
      equal   = (memcmp( (void *) public_var, (void *) copy_var, nobytes )
                    == 0 ) ;
   }

   return equal ;
}

